### ISSUE TITLE
Milestone 1 assignments

### ISSUE THREAD

**Issue by flizhou** [UBC-MDS/DSCI_522_Group_301#1]
- [x] 1. Team work contract (Fanli)

- [x] 2. Code of conduct (Margaret)

- [x] 3. Contribu(Margaret)

- [x] 4. license

- [x] 5. Project proposal (Margaret, Fanli)
- Dataset: Breast Cancer Data Set
- Research question: 
Main research question: 
What are the strongest predictors of breast cancer recurrence?  (Predictive)
Sub research question:
What is the rate of breast cancer recurrence in the data set? (Descriptive)
Is there any relation between age and breast cancer recurrence? (Exploratory)
Is there any relation between tumor-size and breast cancer recurrence? (Exploratory) 
- Plan: classification, logistic regression
- Discuss tables and figures
- Suggest how to share the result
   weights table/bar graph 

- [x] 6. A script
In python.  [Fanli]

- [x] 7. EDA (Clara, Margaret, Fanli)
In python
