### ISSUE TITLE
Milestone 3 Assignment 

### ISSUE THREAD

**Issue by clsu22** [UBC-MDS/DSCI_522_Group_301#40]
- [ ]  Modify code wrangling @clsu22 
- [ ]  Added tests in script @flizhou @Margaret8521  @clsu22 
- [x] Check README command @Margaret8521 
- [x] Create make file @flizhou
