### ISSUE TITLE
Milestone 4

### ISSUE THREAD

**Issue by flizhou** [UBC-MDS/DSCI_522_Group_301#55]
- [x] Improve report based on visualizations feedback issue #54  @flizhou 

- [x] Makefile visualization @Margaret8521 

- [x] Dockerfile @clsu22 

- [x] Try the `class-weight` hyperparameter for `LogisticRegression` @Margaret8521
